import { model, Model, Schema } from "mongoose";
import IStudents from "../interfaces/IStudents";

const studentSchema = new Schema({
    nis: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    nama: { type: String, required: true },
    jenis_kelamin: { type: Schema.Types.ObjectId, ref: "gender" },
    nisn: { type: String, required: true, unique: true },
    tempat_lahir: { type: String, required: true },
    nik: { type: String, required: true },
    agama: { type: Schema.Types.ObjectId, ref: "religion" },
    kebutuhan_khusus: { type: String, required: true },
    alamat: { type: String, required: true },
    rt: { type: String, required: true },
    rw: { type: String, required: true },
    dusun: { type: String, required: true },
    kelurahan: { type: String, required: true },
    kecamatan: { type: String, required: true },
    kode_pos: { type: Number, required: true },
    jenis_tinggal: { type: String, required: true },
    alat_transportasi: { type: String, required: true },
    telepon: { type: String, required: true },
    hp: { type: String, required: true },
    email: { type: String, required: true },
    foto: { type: String, required: true },
    nama_ayah: { type: String, required: true },
    tahun_lahir_ayah: { type: Number, required: true },
    pendidikan_ayah: { type: String, required: true },
    pekerjaan_ayah: { type: String, required: true },
    penghasilan_ayah: { type: String, required: true },
    kebutuhan_khusus_ayah: { type: String, required: true },
    no_telepon_ayah: { type: String, required: true },
    nama_ibu: { type: String, required: true },
    tahun_lahir_ibu: { type: Number, required: true },
    pendidikan_ibu: { type: String, required: true },
    pekerjaan_ibu: { type: String, required: true },
    penghasilan_ibu: { type: String, required: true },
    kebutuhan_khusus_ibu: { type: String, required: true },
    no_telepon_ibu: { type: String, required: true },
    nama_wali: { type: String, required: true, default: "" },
    tahun_lahir_wali: { type: Number, required: true, default: 0 },
    pendidikan_wali: { type: String, required: true, default: "" },
    pekerjaan_wali: { type: String, required: true, default: "" },
    penghasilan_wali: { type: String, required: true, default: "" },
    angkatan: { type: Number, required: true },
    status_siswa: {
        type: String,
        enum: ["Aktif", "Tidak Aktif"],
        default: "Aktif",
    },
    kelas: { type: Schema.Types.ObjectId, ref: "classes" },
    jurusan: { type: Schema.Types.ObjectId, ref: "major" },
});

const Student: Model<IStudents> = model<IStudents>("student", studentSchema);
export default Student;
